CREATE DATABASE IF NOT EXISTS mini_boards;

USE mini_boards;

DROP TABLE IF EXISTS boards;

CREATE TABLE boards(
	id				BIGINT(20) UNSIGNED PRIMARY KEY AUTO_INCREMENT
	,title		VARCHAR(50) NOT NULL
	,content 	VARCHAR(1000) NOT NULL
	,created_at	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP()
	,updated_at	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP()
	,deleted_at	TIMESTAMP
);